steps:
  # Docker 이미지를 빌드합니다
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/jap-bong-pro:$COMMIT_SHA', '.']

  # 이미지를 Container Registry에 푸시합니다
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/jap-bong-pro:$COMMIT_SHA']

  # Cloud Run에 배포합니다
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'jap-bong-pro'
      - '--image'
      - 'gcr.io/$PROJECT_ID/jap-bong-pro:$COMMIT_SHA'
      - '--region'
      - 'asia-northeast3'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'GEMINI_API_KEY=$_GEMINI_API_KEY,NAVER_CLIENT_ID=$_NAVER_CLIENT_ID,NAVER_CLIENT_SECRET=$_NAVER_CLIENT_SECRET,GITHUB_PAT=$_GITHUB_PAT,GITHUB_REPO=$_GITHUB_REPO'

images:
  - 'gcr.io/$PROJECT_ID/jap-bong-pro:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
